### ISSUE TITLE
ping and feature request

### ISSUE THREAD

**Issue by drizuid** [GreatWizard/lan-play-status#25]
When i first submitted my server (joinsg.net) i forgot i had pings blocked. For now, i've opened ping to all but I would prefer to restrict ICMP to the ip (or subnet) you source your pings from.  I am on discord if you would prefer to DM this. 

Further, since i enabled pings, i still show n/a on the ping column so perhaps this does not poll very often at all. 

Finally, it would be great to see another column for uptime to easily recognize more reliable (read: high uptime) servers.   thanks for all you do!

**Comment by GreatWizard** [comment]
Hello,

Ping is not performed by the ICPM protocol.

There are 2 situations:
- node / dotnet server: when we obtain the data by API, then we compute the duration to do the request and we apply a correction (due to the serialization / deserialization of the data by the browser)
- server rust, we use the same principle but being connected in websocket to the graphql server embedded with the server

You don't have to configure anything to let the PING computed correctly.

There are issues with CORS on HTTPS, that why we redirect HTTPS onto HTTP by default.
It's a read-only website so there is no risk to not use a secure connection.


---

About the uptime, that can be more complicated because I need ot setup a cron check and store data somewhere. It's a bit out the scope of the current generated static website.
But that can be done pretty easily.
I wonder if there is a good (and free 🤞) web-service to store statistic data?
I can setup a cron to check status on my server.

**Comment by GreatWizard** [comment]
About uptime, I'm giving a try to uptimerobot.com
I seems to do the job well. I will work on an integration this week

**Comment by drizuid** [comment]
hey, thanks for the reply! Makes a lot of sense. I just panicked a little when i saw some nodejs nodes showing latency and not mine :D my rust shows it fine and i think most users are preferring the rust server anyway. 

uptime robot looks super cool. I actually use [statping](https://github.com/statping/statping) (in a docker container) and have it report to discord when a service fails the check. While I imagine you could leverage the data on your site, i think uptimerobot may be a better fit?

Anyway, if you're not using this to link to a PR, please feel free to close it, i think you answered all of my questions quite well! thanks for all you do!

**Comment by GreatWizard** [comment]
I setup uptimerobot and it seems quite nice :)
Let's see on the long terms but right now the uptime ratio is on the website ;)

**Comment by Stuntaneous** [comment]
auslanplay.ddns.net:11451 is not showing a ping on the site. What can I do to fix this?

**Comment by GreatWizard** [comment]
You are on a node server, I guess ou use a clone of the github repo in order to run your server?
Can you check that you are up-to-date with github? and rebuild the typescript into JS in order to have the last changes.

I made a fix october 2018 in order to have ping working on the node server: https://github.com/spacemeowx2/switch-lan-play/commits/master/server It's quite old.

**Comment by Stuntaneous** [comment]
I'm using the Docker container (spacemeowx2/switch-lan-play). Will it be updated or should I go to compiling it?

**Comment by GreatWizard** [comment]
I have no idea what is in the docker image. it's probabbly quite old.
If you are updating your server, if I were you, I will go on the rust server which is maitained by spacemeowx2 and have better performance

**Comment by Stuntaneous** [comment]
Alrighty, I'll do that. Thanks :)
